config/routes.rb
Polls::Application.routes.draw do
  
  root :to => 'polls#index'
  
  get "force_sessions/create"
  get "sfdcauth", to: 'force_session#authorize'  
  
  resources :votes

  resources :polls 

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :poll
  has_many :votes
  attr_accessible :answer_text
end

app/models/env_config.rb
class EnvConfig < ActiveRecord::Base
  attr_accessible :name, :value
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :gl_id, :name
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :answers
  attr_accessible :question, :sfid
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :player
   attr_accessible :answer_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/force_session_controller.rb
require 'net/http'

class ForceSessionController < ApplicationController
 
  def authorize


    
    
    uri = URI.parse("https://login.salesforce.com")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Post.new('/services/oauth2/token')
    request.add_field('Content-Type', 'application/x-www-form-urlencoded')

    crypt = ActiveSupport::MessageEncryptor.new(ENV['DB_TOKEN'])

    code = CGI::escape(params['code'])
    client_id = crypt.decrypt_and_verify(EnvConfig.where(name: 'SF_CLIENT_ID').first.value)
    client_secret = crypt.decrypt_and_verify(EnvConfig.where(name: 'SF_CLIENT_SECRET').first.value)
    request.body = "code=#{code}&grant_type=authorization_code&client_id=#{client_id}&client_secret=#{client_secret}&redirect_uri=#{ENV['REDIRECT_URL']}"

    response = http.request(request)

    data = JSON.parse(response.body)

    id = data['id']
    refresh_token = data['refresh_token']
    instance_url = data['instance_url']
    signature = data['signature']
    access_token = data['access_token']


    if id
      save_config(crypt, 'SF_ID', id)
    end

    if refresh_token
      save_config(crypt, 'SF_REFRESH_TOKEN', refresh_token)
    end

    if instance_url
      save_config(crypt, 'SF_INSTANCE_URL', instance_url)
    end

    if signature
      save_config(crypt, 'SF_SIGNATURE', signature)
    end

    if access_token
      save_config(crypt, 'SF_ACCESS_TOKEN', access_token)
    end

    render text: "Done"
  end

  def save_config(crypt, name, value)
    config = EnvConfig.where(name: name).first
    if !config
      config = EnvConfig.new
      config.name = name
    end
    config.value = crypt.encrypt_and_sign(value)
    config.save
  end
  
  
  def create
  
    crypt = ActiveSupport::MessageEncryptor.new(ENV['DB_TOKEN'])
    
    config = EnvConfig.where(name: 'SF_TOKEN').first
    if !config
      config = EnvConfig.new
      config.name = 'SF_TOKEN'
    end
    config.value = crypt.encrypt_and_sign(request.env['omniauth.auth']['credentials']['token'])
    config.save
  
    config = EnvConfig.where(name: 'SF_INSTANCE_URL').first
    if !config
      config = EnvConfig.new
      config.name = 'SF_INSTANCE_URL'
    end
    config.value = crypt.encrypt_and_sign(request.env['omniauth.auth']['instance_url'])
    config.save
    
    render :text => request.env['omniauth.auth'].inspect
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.order("created_at")
    poll = @polls.first
    if poll
      redirect_to @polls.first
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @polls }
      end
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll }
    end
  end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new
    
    @vote.answer_id = params[:answer_id]
    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer_text %><br />
    <%= f.text_field :answer_text %>
  </div>
  <div class="field">
    <%= f.label :poll %><br />
    <%= f.text_field :poll %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Answer text</th>
    <th>Poll</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.answer_text %></td>
    <td><%= answer.poll %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer text:</b>
  <%= @answer.answer_text %>
</p>

<p>
  <b>Poll:</b>
  <%= @answer.poll %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polls</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gl_id %><br />
    <%= f.text_field :gl_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Gl</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.gl_id %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<p>
  <b>Gl:</b>
  <%= @player.gl_id %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :sfid %><br />
    <%= f.text_field :sfid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<div class='quest'>
<h2>
  Polls!
</h2>


</div>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<div class='quest'>
<h2>
  <%= @poll.question %>
</h2>

<ul>
<% @poll.answers.each do |ans| %>
<li><%= button_to ans.answer_text, {:controller => "votes", :action => "create", :answer_id => ans.id}, :method=>:post, :class => 'votebutton'  %></li>
<% end %>	
	
</ul>
</div>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :player %><br />
    <%= f.text_field :player %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>Answer</th>
    <th>Player</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.answer %></td>
    <td><%= vote.player %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<div class='quest'>
<h2>
  Thanks for voting!
</h2>


</div>